### ISSUE TITLE
package.json does not have dependencies

### ISSUE THREAD

**Issue by ssanyal** [cutsin/require-yml#12]
const fs = require('fs')
const path = require('path')
const parser = require('js-yaml')

these are packages are missing in the package json

**Comment by ssanyal** [comment]
Issue with webapack and fs

**Comment by osher** [comment]
@ssanyal
both `fs` and `path` are built-in nodejs - where the package is meant for use in node-js and does not make sense out of it.

@cutsin  - I think this issue should be closed
