### ISSUE TITLE
Improvement: cascading between files of different extensions

### ISSUE THREAD

**Issue by osher** [cutsin/require-yml#8]
### cascading
As a configuration provider
When I provide a directory with same file-name and different extensions
I would like all the configurations to be merged together
So that I can express different info in it's best suited dialect.

### custom cascade order
As a configuration provider
When I provide a directory with same file-name and different extensions
I would like to be able to control what extension has the last word
So that I customize a predictable deterministic behavior

## Similar packages

Consider the npm package `config`:
```
~/osher/sandbox cat tmp/default.yml  
a: a-yml
b: b-yml
~/osher/sandbox cat tmp/default.js 
exports.b = 'c-js'
exports.c = 'c-js'
~/osher/sandbox node
> process.env.NODE_CONFIG_DIR = './tmp'
'./tmp'
> require('config')
Config { b: 'b-yml', c: 'c-js', a: 'a-yml' }
> 
```
What is observed here is that `config` merges all files it finds, where `.yml` has the last word, as demonstrated by the key `b`.
(probably because that's how it's ordered on my ubuntu by `fs.readDirSync`)

## Proposed Solutions

About _**cascading**_ - it's easy:
use an overridable default `req.merge = (a,b) => b`

Users that want a custom merge can implement it themselves (probably by `req.merge = require('lodash/merge')` or their own handler based on `lodash/mergeWith` with their own logic of how to handle arrays and so.

About _**custom cascade order**_ - we can go few ways.
1. use `.sort()` on `.readdirSync` to impose determinism. Determinism guaranteed, but no user control supported.

2. allow another singleton-level setting (like `req.merge` and `req.onLoadError`).
e.g.
`req.extensions =  ['.yml', '.yaml', '.json', '.js']`
Which is basically the same internal var seen [here](https://github.com/cutsin/require-yml/blob/master/index.js#L7) 

And use it when reading directories in [here](https://github.com/cutsin/require-yml/blob/master/index.js#L38) like so:

```
    var dirFiles = fs.readdirSync(target)
    var files = req.extensions.map(ext => difFiles.filter(file => file.endsWith(ext))
    files = [].concat(...files)//i.e - flatten
```

**Comment by osher** [comment]
If we're already here - I suggest to expose a factory that will let users provide all their settings in an options object instead of assigning to a singleton-level attributes.

e.g.:
```
const req = require('require-yaml').custom({
  extensions: [ ".js", "json", "yml" ],
  onLoadError(err) { ... },
  onParseError(err) { ... },
  onItrError(err) { .. },
  merge(current, new) { ... },
})

const config = req('./demo-dir`)
```

I would like to hear what feel about this before I proceed to making a PR.
I tried to do my best to keep the API compatible with previous versions.

Also - would like the PR to modernize the syntax ? 
(i.e - `var` -> `const/let`, `function` -> ` => `, etc)

**Comment by cutsin** [comment]
Sounds good🙂, but I'm not sure if this might complicate the package itself (except for the exception handling part)

**Comment by osher** [comment]
I would like you to feel comfortable with the proposed changes. Let me explain why I don't think it will complicate:

The essence of the change is to wrap the same code that declare the `req` signleton with a factory function, and for example - call it `function ymlLoaderFactory(options) { ... }`, wrapping everything we've got, with a single difference - returning `req` instead of assigning  `module.exports = req`.

Then, export an instance that is produced by this factory with default settings function. 
And - last - expose the factory itself as `req.custom = ymlLoaderFactory`

e.g. :
```
cosnt req = module.exports = ymlLoaderFactory({ 
    /* here be the baked-in defaults */
})

req.custom = ymlLoaderFactory;

function ymlLoaderFactory(options) {
   /*
      here be most of what we have today, with slight changes 
      assigning everything from options to req, 
      or taking custom behavior from `options` instead of from `req`

      every time this factory is called - a new closure is produced with it's own settings :)
   */

  return req
}
```

Although most of the code should stay the same - you will see a change in every line - but mostly because of white-spaces...

Anyway - the result will be an exported singleton that works with full compatibility to currently published version, and new a `.custom(options)` method that creates custom instances.


If we're also  modernizing to ES6 - then although it's a fully compatible version - I would consider to jump a major.
I think it's relevant to modernize, because the node LTS is v10, and ES6 has been introduced already in node 8.
ES6 means using consts, arrow functions and destructors.

We can also consider  to support a `req.async(path) -> Promise`, that uses async APIs, but I don't think it's really necessary because the library is mainly used for configurations loaded at startup, and would like to work on it on a separate PR when a concrete need appears.

Another modernizing change can be to support `req(arrPaths)` as well as `req(path)`, which is just a few lines of code (e.g `if ('string' == typeof arrPaths) arrPaths = [ arrPaths ]`, and looping arrPaths).

Jumping a version will allow to keep `v1.x` for very old versions of node with current behavior.
And if we're jumping a major - I'll advise to provide safer defaults -  e.g = `onLoadError = e => { throw e }` which is a breaking change.

If you feel OK with this course - I will do it :)
If you would like me to do just part of it - let me know, I'll focus my efforts in the proposals you would like to adopt.
You can also ask me to do the changes over gradual PRs:
1. factorize
2. modernize (depends on factorize)
3. support `req(arrPaths)` (depends on factorize and modernize)
4, support `req.promise(arrPaths)`  (depends on factorize and modernize)

**Comment by osher** [comment]
hmm. 
There's another style we can consider. Sorry for the noise, but give me a while to present it.

**Comment by osher** [comment]
There is another style you can consider to adopt as an alternative to the factorization.

The essence of this change is to move from `req(path, itr)` to `req(options)` - which I now think could present a cleaner API.

- New API expects options object.
- Backward compatibility is done by type-overloading and defaulting to args of old style.

e.g.
```
function req(options) {
    if ('string' == typeof options) options = [ options ]
    if (Array.isArray(options)) options = { paths: options }
    const throwErr = e => { throw e }
    const {
       iterator = arguments[1],
       onLoadError = throwErr,
       onParseError = throwErr,
       onItratorError = throwErr,
       extensions = ['.yml', '.yaml', '.json', '.js'],
       merge = (current, loaded) => loaded,
    } = options

    /* here be what we have here, adjusted to use destrutured options */
```

I hope you like this better. It should also produce fewer changes :grinning: 

I still propose the additional changes, which you can ask in one PR or in few PRs, and would like to know your opinion regarding jumping a major version.

Lets call this style `req(options)`, and it replaces `factorize` in the multiple PR proposal.

**Comment by cutsin** [comment]
Hmm, I'm pretty sure you can do it and look forward to your PR😀

**Comment by osher** [comment]
Can I use ES6, or stick to ES5?

**Comment by cutsin** [comment]
Yes please, it could be a major change

**Comment by osher** [comment]
I've started. But OMG - I forgot why I had to go to the factory pattern in the first place :cry: 

it's because of the signature of the exported `req`:
```
function req(target, iterator, cb)
```
This makes it impossible to distinct reliably between `(options, cb)` and `(options, itr)`.
The danger is user-error of missing `null` as 2nd parameter to explain they mean a callback.

We have the following options.
please LMK **which of the options do you believe is best?**

1. be concise: do not support a callback on `req`, but expose `req.async(cb)`  that works synchronously behind the scene like we do now... :stuck_out_tongue:. 
In this case we can even return a promise when it's called without a `cb` :grin:
2.  use the factory pattern... - but now I think it does not fully rid us of user errors forgetting to give `null` in 2nd argument.
3.  do a best-effort guesswork in the spirit of logic below. Should be easier on users to migrate, but also makes code longer and needs more tests.

```
const req(options, iterator, cb) => {
  //try to maintain backward compatibility
  if ('object' == typeof options && 'function' == typeof iterator && !cb) {
     //object is a newer form. object can include iterator. user means a callback
     [iterator, cb] = [null, iterator]
  }
  if ('string' == typeof options) options = { target: options }
  if ('function' == typeof iterator) options.iterator = iterator

  if ('function' == typeof cb) {
    process.nextTick(() => cb read(options)))
    return 
  }

  return read(options)
}
```

**Comment by osher** [comment]
I've started work here: #9
Please do not merge - there are open issues.
Would be happy to continue there
Let me have your thoughts.
